services:
  db:
    image: icr.io/db2_community/db2:11.5.9.0
    platform: linux/amd64
    privileged: true
    environment:
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: db2inst1
      DBNAME: appdb
      LICENSE: accept
    ports:
      - "50000:50000"
    volumes:
      - db2data:/database
    healthcheck:
      test: ["CMD-SHELL", "su - db2inst1 -c 'db2 connect to appdb'>/dev/null && echo 'healthy' || echo 'not healthy'"]
      interval: 30s
      timeout: 10s
      retries: 10

  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5187
      DB2_USER: db2inst1
      DB2_PASSWORD: db2inst1
      ConnectionStrings__Default: Server=db:50000;Database=appdb;User ID=${DB2_USER};Password=${DB2_PASSWORD};persist security info=true;
    volumes:
      - ./src/Api:/src:cached
    command: bash -c "dotnet restore && dotnet run --urls http://0.0.0.0:5187"
    ports:
      - "5187:5187"

volumes:
  db2data:
